FIAT/P0.py, FIAT/discontinuous_pc.py, FIAT/reference_element.py, FIAT/serendipity.py
Fixed the Serendipity and dPc elements on TPCs. A new function flatten_reference_element maps the TPC onto a UFC cell where the element is constructed. The entity dofs are then mapped back to the corresponding TPC numbering.
=> Serendipity and dPc fix on TPCs

FIAT/P0.py, FIAT/discontinuous_lagrange.py, FIAT/dual_set.py, FIAT/finite_element.py, FIAT/gauss_legendre.py, FIAT/gauss_lobatto_legendre.py, FIAT/lagrange.py, FIAT/reference_element.py
This PR is to attach `entity_permutations` `dict` to basic finite elements (such as `Lagrange`) that defines a DoF permutation (to be used in global vector assembly) for each possible entity orientation for each entity for each dimension. 
`entity_permutations` is set `None` if it is not yet implemented for that element, so the problem solving environment must handle this correctly if it ever tries to access this attribute.
This is intended to be the first step for FIAT to handle orientations.
=> orientations: define entity_permutations for CG and DG elements

test/unit/test_awc.py, test/unit/test_awnc.py, test/unit/test_mtw.py
As per the Slack discussion on 13th Jan '22, change the domains of the tests of the zany AWc, AWnc, and MTW elements from a random triangle to (as suggested by @rckirby) a fixed rotation and shear of the unit triangle, to avoid the error encountered by @pbrubeck. Note that in `test_awc.py`, the domains of `test_dofs` and `test_projection` are (still) different.
=> Turn off randomisation of the test domains of the AWc, AWnc, and MTW elements.

FIAT/__init__.py, FIAT/barycentric_interpolation.py, FIAT/fdm_element.py, test/unit/test_fdm.py
This element uses shape functions that diagonalize the Laplacian stiffness and the mass matrix (or equivalently the H1 Riesz map) on the interior of the interval, and has additional point evaluation nodes at the vertices to enforce continuity when required.
This element produces a sparse stiffness matrix for certain symmetric and coercieve forms with constant coefficients discretized with CG/IPDG. 
More details can be found [here](https://arxiv.org/abs/2107.14758).
=> Added CG/DG element with FDM shape functions

FIAT/dual_set.py
Users might want to call `to_riesz` on other expansion sets to e.g. evaluate the dual directly with FIAT, so there is no need to keep the result as an attribute.
=> Remove mat attribute within DualSet.to_riesz

FIAT/reference_element.py
-0.0 can be converted to a small negative number during code generation
=> Avoid returning -0.0 from distance_to_point_l1

FIAT/gauss_lobatto_legendre.py, FIAT/lagrange.py
Add variant kwarg to `Lagrange`, `GaussLobattoLegendre` subclasses `Lagrange`
=> Lagrange variants

FIAT/barycentric_interpolation.py, FIAT/expansions.py, FIAT/lagrange.py, FIAT/nodal_enriched.py, FIAT/polynomial_set.py, test/unit/test_fiat.py
`NodalEnrichedElements` of mixed degree would break with elements using `LagrangeExpansionSets` if the first element is not the embedding one, e.g `Lagrange(interval, 1) + Bubble(interval, 2)`. LagrangeExpansionSets can only tabulate a fixed number of polynomials. This was not an issue with the Dubiner `ExpansionSet`, as these `ExpansionSets` do not have a fixed degree. 
Here we fix this by ensuring the resulting `NodalEnrichedElement` uses the `ExpansionSet` of the element that dictates the embedding degree.
=> Ensure EnrichedElement uses the embedding ExpansionSet

FIAT/finite_element.py
I guess the code here was trying to make any warnings related to the enclosed LU factorisation/solve into errors, but it was then resetting the entire warnings filter. This shouldn't be done from library code, the pattern should be to use the catch_warnings context manager to ensure the previous state is restored.
(I don't know if PRs should go here, or upstream?)
=> Don't reset all warning filters on element construction

FIAT/P0.py, FIAT/__init__.py, FIAT/barycentric_interpolation.py, FIAT/check_format_variant.py, FIAT/discontinuous_lagrange.py, FIAT/discontinuous_pc.py, FIAT/dual_set.py, FIAT/expansions.py, FIAT/finite_element.py, FIAT/gauss_legendre.py, FIAT/gauss_lobatto_legendre.py, FIAT/hct.py, FIAT/hierarchical.py, FIAT/hsieh_clough_tocher.py, FIAT/jacobi.py, FIAT/lagrange.py, FIAT/macro.py, FIAT/morley.py, FIAT/polynomial_set.py, FIAT/quadrature.py, FIAT/quadrature_schemes.py, FIAT/reference_element.py, test/regression/test_regression.py, test/unit/test_fiat.py, test/unit/test_hct.py, test/unit/test_macro.py
Extend `Simplex` to `SimplicialComplex` with minimal changes.
Implement `SplitSimplicialComplex` and `AlfeldSplit` and `IsoSplit` subclasses, which take a parent simplex in the constructor.  
`DualSet` on a `SplitSimplicialComplex` merges the entities DOFs on the complex onto the parent entites.
`ExpansionSet` loops across subcells and does indirection to evaluate the hierarchical DG or CG basis functions.
`FiniteElement` gets a reference complex attached to in, in case we want to expose the split to define quadrature rules. `CiarletElement` will infer the reference complex from the underlying polynomial space.
`create_quadrature` returns a `MacroQuadrature` rule on macro cells.
=> Implement C0/C1 macroelements

FIAT/hct.py, test/unit/test_argyris.py
After adding more rigorous tests, turns out the the Jacobi weights for HCT must be (1, 1) to obtain a hierarchial basis. This requires a slightly specialized treatment for the basis transformation in FInAT.
=> HCT: ensure hierarchical edge basis functions

FIAT/Sminus.py, FIAT/SminusCurl.py, FIAT/SminusDiv.py, FIAT/bernstein.py, FIAT/dual_set.py, FIAT/expansions.py, FIAT/finite_element.py, FIAT/macro.py, FIAT/reference_element.py, FIAT/serendipity.py, test/unit/test_gauss_legendre.py, test/unit/test_gauss_lobatto_legendre.py, test/unit/test_hdivtrace.py, test/unit/test_macro.py, test/unit/test_reference_element.py
Update `cell_point_map` to bin points to the nearest cell. This is required for non-nested multigrid, enabling extrapolation when the children cells fall outside the parent cell.
This PR also includes some cleanup that favors numpy over list-comprehensions.
=> Macro: bin points to nearest cell

FIAT/orientation_utils.py, FIAT/quadrature.py, FIAT/reference_element.py
Add methods in `Cell` that return:
- a map from orientations to the corresponding axis permutation matrix.
- a map from orientations to the corresponding point/DoF permutation arrays.
=> hex: enable interior facet integration

FIAT/__init__.py, FIAT/macro.py, finat/__init__.py, finat/element_factory.py, finat/ufl/elementlist.py, test/finat/test_create_fiat_element.py, test/finat/test_create_finat_element.py
With this PR, adding a new element to Firedrake would only require modifying the FIAT repo.
Firedrake PR: https://github.com/firedrakeproject/firedrake/pull/3929
=> Single source of truth

FIAT/bernstein.py
This should allow `interpolate`, `prolong`, `inject` to Just Work in Firedrake.  Are there any complications that arise from doing this?  And will it somehow allow native transfers for MG to work in FD also?
=> Turn on a pointwise dual in Bernstein

FIAT/macro.py, FIAT/reference_element.py, test/FIAT/unit/test_macro.py
Make `ref_el` agree across different split elements.
=> Cache split cells

FIAT/functional.py
These are just some preparations to implement more zany elements with derivative dofs.
=> Add more functionals

FIAT/nedelec.py, FIAT/polynomial_set.py, FIAT/raviart_thomas.py, test/FIAT/unit/test_polynomial.py
Add extension of coefficients to allow union of polysets with different degrees.
This is the same code as in #127 but without all the FUSE specific content.
=> Extend PolySet coefficients

FIAT/reference_element.py, finat/point_set.py, finat/quadrature.py, gem/utils.py, test/finat/test_create_fiat_element.py, test/finat/test_quadrature.py
Also remove some uses of deprecated `@abstractproperty` and gives cells and point sets `repr()`s.
Necessary for https://github.com/firedrakeproject/firedrake/pull/3989
=> Fix quadrature rule hash

FIAT/bernstein.py, FIAT/expansions.py, FIAT/jacobi.py, test/FIAT/unit/test_fiat.py
Ensure that `element.tabulate(0, point)` returns a vector as opposed to a matrix.
=> Fix single point tabulation for DG0

FIAT/discontinuous.py
`DiscontinuousElement` did not set a `ref_complex` attribute, nor implemented `get_reference_complex()`.
This PR initializes the basic attributes of `DiscontinuousElement` by calling `FiniteElement.__init__`. We do not want to call `CiarletElement.__init__` here, as it will retrigger the solution of the Vandermonde system.
=> DiscontinuousElement: stash missing attributes

pyproject.toml
Fixes https://github.com/firedrakeproject/fiat/issues/141
I think `firedrake-fiat` is very clear, but happy to change based on popular opinion. @rckirby @pbrubeck ?
Also this definitely has to happen because we don't own `fenics-fiat` on PyPI.
=> Rename pypi package

FIAT/bubble.py, FIAT/hdiv_trace.py, finat/element_factory.py, finat/fiat_elements.py, test/FIAT/unit/test_fiat.py, test/FIAT/unit/test_hdivtrace.py
This PR enables general variants for `Bubble`, `FacetBubble`, and `HDivTrace`.
Additionally, it also enables `HDivTrace` to be tabulated on multiple facets at a time. The previous behaviour allowed tabulation on points defined on a cell as long as the points were on the same facet.
=> Bubble Lagrange variants and multiple facet HDivTrace tabulations

FIAT/fdm_element.py, FIAT/hierarchical.py, FIAT/polynomial_set.py, FIAT/restricted.py, finat/restricted.py
Fixes https://github.com/firedrakeproject/firedrake/issues/4467
Also refactoring hierarchical.py and fdm_element.py
To deal with the orientation problem (the mapping from the reference to the physical cell is unique up to permutations of the vertices), Firedrake has two mechanisms to generate a local to global mapping. The first one is to number dofs within an entity with increasing global vertex id. This option has the advantage that one only needs to deal with a fixed ordering of the degrees of freedom for every cell, but the resulting ordering is not robust with respect to the mesh distribution. The robust alternative involves a transformation of degrees of freedom for every possible permutation of the vertices of the reference element.
The `entity_permutations` indicate how to …
=> Remove entity permutations for non-Lagrange elements
